import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import Footer from "./components/footer/Footer";
import CartProvider from "@/providers/CartProvider";
import { Toaster } from "react-hot-toast";


const poppins = Poppins({
  subsets: ["latin"],
  weight: "400"
});
export const metadata: Metadata = {
  title: "XT-shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
          <Toaster 
          toastOptions={{
            style:{
              background:"rgb(51 65 85)",
              color:'#fff'
            }
          }}/>
          <CartProvider>
            <NavBar/>
              {children}
            <Footer/>
          </CartProvider>
        </body>
    </html>
  );
}
